CREATE DEFINER=`root`@`localhost` PROCEDURE `gerarGruposCampeonato`()
BEGIN
DECLARE RESULTADO_REGISTROS_ALEATORIOS INT;
DECLARE RESULTADO_CONSULTA_GRUPO_EXISTENTE INT;
DECLARE NOVO_TIME INT;
DECLARE CONTADOR INT;
DECLARE AUXILIAR INT;
DECLARE RESULTADO_CONSULTA_GRUPO INT;

SET RESULTADO_CONSULTA_GRUPO = (SELECT CODIGO_TIME FROM GRUPOS ORDER BY RAND() LIMIT 1);
	IF RESULTADO_CONSULTA_GRUPO IS NOT NULL THEN 
	SELECT 'EXCLUINDO GRUPOS EXISTENTES PARA A GERACAO DE NOVOS';
		UPDATE CONTROLE_GERACAO_GRUPOS SET INDICADOR_PRESENTE_GRUPO = 'N';
		DELETE FROM GRUPOS;
	END IF;

SET CONTADOR = 0;
SELECT 'INICIANDO GERACAO DO GRUPO A...';
	WHILE CONTADOR < 4 DO
		SET RESULTADO_REGISTROS_ALEATORIOS = (SELECT CODIGO_TIME FROM CONTROLE_GERACAO_GRUPOS WHERE INDICADOR_PRESENTE_GRUPO = 'N'  ORDER BY RAND() LIMIT 1);

        INSERT INTO GRUPOS VALUES ('A', RESULTADO_REGISTROS_ALEATORIOS);
        UPDATE CONTROLE_GERACAO_GRUPOS SET INDICADOR_PRESENTE_GRUPO = 'S' WHERE CODIGO_TIME = RESULTADO_REGISTROS_ALEATORIOS; 
		
		SET CONTADOR = CONTADOR + 1;
	END WHILE;
SET CONTADOR = 4;
SELECT 'INICIANDO GERACAO DO GRUPO B...';
	WHILE CONTADOR < 8 DO
		SET RESULTADO_REGISTROS_ALEATORIOS = (SELECT CODIGO_TIME FROM CONTROLE_GERACAO_GRUPOS WHERE INDICADOR_PRESENTE_GRUPO = 'N'  ORDER BY RAND() LIMIT 1);

        INSERT INTO GRUPOS VALUES ('B', RESULTADO_REGISTROS_ALEATORIOS);
        UPDATE CONTROLE_GERACAO_GRUPOS SET INDICADOR_PRESENTE_GRUPO = 'S' WHERE CODIGO_TIME = RESULTADO_REGISTROS_ALEATORIOS; 
		
		SET CONTADOR = CONTADOR + 1;
	END WHILE;

SET CONTADOR = 8;

SELECT 'INICIANDO GERACAO DO GRUPO C...';
	WHILE CONTADOR < 12 DO
		SET RESULTADO_REGISTROS_ALEATORIOS = (SELECT CODIGO_TIME FROM CONTROLE_GERACAO_GRUPOS WHERE INDICADOR_PRESENTE_GRUPO = 'N'  ORDER BY RAND() LIMIT 1);

        INSERT INTO GRUPOS VALUES ('C', RESULTADO_REGISTROS_ALEATORIOS);
        UPDATE CONTROLE_GERACAO_GRUPOS SET INDICADOR_PRESENTE_GRUPO = 'S' WHERE CODIGO_TIME = RESULTADO_REGISTROS_ALEATORIOS; 
		
		SET CONTADOR = CONTADOR + 1;
	END WHILE;
SET CONTADOR = 12;

SELECT 'INICIANDO GERACAO DO GRUPO D...';
	WHILE CONTADOR < 16 DO
		SET RESULTADO_REGISTROS_ALEATORIOS = (SELECT CODIGO_TIME FROM CONTROLE_GERACAO_GRUPOS WHERE INDICADOR_PRESENTE_GRUPO = 'N'  ORDER BY RAND() LIMIT 1);

        INSERT INTO GRUPOS VALUES ('D', RESULTADO_REGISTROS_ALEATORIOS);
        UPDATE CONTROLE_GERACAO_GRUPOS SET INDICADOR_PRESENTE_GRUPO = 'S' WHERE CODIGO_TIME = RESULTADO_REGISTROS_ALEATORIOS; 
		
		SET CONTADOR = CONTADOR + 1;
	END WHILE;
END