DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `montarConfrontosPaulistao`()
BEGIN

/*VARIAVEIS PARA CONTROLE DA GERACAO DOS JOGOS */
DECLARE CONTADOR INT;
DECLARE DATA_ACONTECIMENTO_JOGO VARCHAR(30);
DECLARE TIME_A INT;
DECLARE TIME_B INT;
DECLARE TOTAL_GOLS_TIME_A INT;
DECLARE TOTAL_GOLS_TIME_B INT;
DECLARE INDICADOR_TIME_MESMO_GRUPO INT;
DECLARE CONTADOR_AUXILIAR INT;
DECLARE CODIGO_GRUPO_AUX CHAR;
DECLARE CONTROLE_COMBINACAO_GRUPO INT;
DECLARE CONTROLE_JOGO_EXISTENTE INT;

SET CONTROLE_JOGO_EXISTENTE = 
(SELECT EXISTS (SELECT CODIGO_TIME_A FROM JOGOS WHERE CODIGO_TIME_A IS NOT NULL));
		IF CONTROLE_JOGO_EXISTENTE = 1 THEN
			SELECT 'LIMPANDO REGISTRO DE JOGOS ANTERIORES...';
			DELETE FROM JOGOS;
		END IF;

SET CONTADOR = 1;
	
		WHILE CONTADOR < 97 DO

			/*GERACAO DE GOLS SERA DE FORMA ALEATORIA*/
			SET TOTAL_GOLS_TIME_A = (SELECT FLOOR(RAND() *10));
            SET TOTAL_GOLS_TIME_B = (SELECT FLOOR(RAND() *10));
			
            SET TIME_A = (SELECT CODIGO_TIME FROM GRUPOS ORDER BY RAND() LIMIT 1);
            SET TIME_B = (SELECT CODIGO_TIME FROM GRUPOS ORDER BY RAND() LIMIT 1);
            	IF TIME_A = TIME_B THEN
            	SELECT 'OPA, UM JOGO NAO PODE ACONTECER COM UM TIME SÓ...';
            		SET TIME_A = (SELECT CODIGO_TIME FROM GRUPOS ORDER BY RAND() LIMIT 1);
            		SET TIME_B = (SELECT CODIGO_TIME FROM GRUPOS ORDER BY RAND() LIMIT 1);
            	END IF;

			SET CONTADOR_AUXILIAR = 0;
            
            	WHILE CONTADOR_AUXILIAR < 16 DO
            		SET CODIGO_GRUPO_AUX = (SELECT CODIGO_GRUPO FROM GRUPOS WHERE NUMERO_SEQUENCIAL_GRUPO = CONTADOR_AUXILIAR);
             		/*VERIFICACAO SE OS TIMES PERTENCEM AO MESMO GRUPO*/
					SET INDICADOR_TIME_MESMO_GRUPO = 
            		(SELECT EXISTS (SELECT CODIGO_TIME FROM GRUPOS WHERE 
						(CODIGO_TIME = TIME_A AND CODIGO_GRUPO = CODIGO_GRUPO_AUX 
                        OR CODIGO_TIME = TIME_B AND CODIGO_GRUPO = CODIGO_GRUPO_AUX)));
						SET CONTADOR_AUXILIAR = CONTADOR_AUXILIAR + 1;
            	END WHILE;
           
				IF INDICADOR_TIME_MESMO_GRUPO = 0 THEN
						SET DATA_ACONTECIMENTO_JOGO = (SELECT DATA_JOGO FROM CALENDARIO_JOGOS WHERE NUMERO_JOGO = CONTADOR);
						INSERT INTO JOGOS (CODIGO_TIME_A, CODIGO_TIME_B, QTD_GOLS_TIME_A, QTD_GOLS_TIME_B, DATA_JOGO)
						VALUES (TIME_A, TIME_B, TOTAL_GOLS_TIME_A, TOTAL_GOLS_TIME_B, DATA_ACONTECIMENTO_JOGO);
					
					ELSE IF INDICADOR_TIME_MESMO_GRUPO = 1 THEN
					 SET DATA_ACONTECIMENTO_JOGO = (SELECT DATA_JOGO FROM CALENDARIO_JOGOS WHERE NUMERO_JOGO = CONTADOR);
					 SET TIME_A = (SELECT CODIGO_TIME FROM GRUPOS WHERE CODIGO_TIME <> TIME_A ORDER BY RAND() LIMIT 1);
					 SET TIME_B = (SELECT CODIGO_TIME FROM GRUPOS WHERE CODIGO_TIME <> TIME_B ORDER BY RAND() LIMIT 1);
						INSERT INTO JOGOS (CODIGO_TIME_A, CODIGO_TIME_B, QTD_GOLS_TIME_A, QTD_GOLS_TIME_B, DATA_JOGO)
						VALUES (TIME_A, TIME_B, TOTAL_GOLS_TIME_A, TOTAL_GOLS_TIME_B, DATA_ACONTECIMENTO_JOGO);
			    	END IF;
				END IF;
           SET CONTADOR = CONTADOR + 1;
        END WHILE;
END$$
DELIMITER ;
